### PR TITLE
Graylog appender + Gelf layout

### PR DESCRIPTION
**Pull request by d-ulyanov**

### CODE REVIEW

**Comment by kategray** [comment]
@rgoers it looks like this was already approved and merged - I'd imagine the PR can be closed.

**Comment by rgoers** [comment]
I agree. Closing.

**Comment by d-ulyanov** [comment]
Funny, I thought that project is dead :)

**Comment by kategray** [comment]
@d-ulyanov It could use some love.  I'm working on it :)

**Pull request closed without merging**
