### PR TITLE
Support logging of PHP 7 error class

### PR DESCRIPTION
**Pull request by czjvic**
We are unable to log PHP Class Error via log4php. There is implemented only logging for Exception class.

### CODE REVIEW

**Review by kategray — COMMENTED** [review]
I don't think this PR is necessary.  My accepted PR already changed the types from Exception to Throwable, which should fix the issue.  @czjvic could you try develop and see if this resolves your issue?

**Comment by kategray** [comment]
@rgoers my recommendation would be to close this issue as resolved, unless @czjvic's issue specifically requires not checking the type of the exception.

**Comment by rgoers** [comment]
Leaving open for now pending feedback.

**Comment by rgoers** [comment]
Closing due to previous comments, conflicts, and the fact that this project is now dormant.

**Pull request closed without merging**
